import type { CardDef } from "./types";

/** Full collectible set — modern combat high-tech + medieval physics theme. */
export const CARD_POOL: CardDef[] = [
  {
    id: "squire",
    name: "Pulse Recruit",
    cost: 1,
    type: "minion",
    attack: 1,
    health: 2,
    text: "1/2 for 1. Light powered armor.",
    art: "steel",
  },
  {
    id: "spark_imp",
    name: "Plasma Spark",
    cost: 1,
    type: "minion",
    attack: 2,
    health: 1,
    text: "2/1 Charge drone. Aggressive open.",
    keywords: ["charge"],
    art: "ember",
  },
  {
    id: "warden",
    name: "Riot Bastion",
    cost: 2,
    type: "minion",
    attack: 1,
    health: 3,
    text: "Taunt. Energy tower shield.",
    keywords: ["taunt"],
    art: "steel",
  },
  {
    id: "arc_blade",
    name: "Laser Edge",
    cost: 2,
    type: "minion",
    attack: 3,
    health: 2,
    text: "3/2 laser blades. Efficient attacker.",
    art: "arcane",
  },
  {
    id: "frost_hound",
    name: "Cryo Hound",
    cost: 2,
    type: "minion",
    attack: 2,
    health: 2,
    text: "Rush — frost laser pet.",
    keywords: ["rush"],
    art: "frost",
  },
  {
    id: "shieldbearer",
    name: "Aegis Operator",
    cost: 3,
    type: "minion",
    attack: 2,
    health: 3,
    text: "Shield projector absorbs first hit.",
    keywords: ["shield"],
    art: "steel",
  },
  {
    id: "blood_leech",
    name: "Nano Leech",
    cost: 3,
    type: "minion",
    attack: 2,
    health: 3,
    text: "Lifesteal siphon beams.",
    keywords: ["lifesteal"],
    art: "shadow",
  },
  {
    id: "iron_colossus",
    name: "Siege Chassis",
    cost: 4,
    type: "minion",
    attack: 3,
    health: 5,
    text: "Taunt. 3/5 laser artillery wall.",
    keywords: ["taunt"],
    art: "steel",
  },
  {
    id: "storm_rider",
    name: "Storm Drone",
    cost: 4,
    type: "minion",
    attack: 4,
    health: 3,
    text: "Charge hover-bike with railguns.",
    keywords: ["charge"],
    art: "frost",
  },
  {
    id: "grove_keeper",
    name: "Bio-Forge Unit",
    cost: 3,
    type: "minion",
    attack: 2,
    health: 4,
    text: "Sturdy 2/4 nanite vines.",
    art: "nature",
  },
  {
    id: "void_knight",
    name: "Void Operative",
    cost: 5,
    type: "minion",
    attack: 4,
    health: 5,
    text: "Shield + void plasma blade.",
    keywords: ["shield"],
    art: "shadow",
  },
  {
    id: "ember_giant",
    name: "Magma Titan",
    cost: 6,
    type: "minion",
    attack: 6,
    health: 6,
    text: "6/6 lava reactor giant.",
    art: "ember",
  },
  {
    id: "prism_titan",
    name: "Prism Battery",
    cost: 7,
    type: "minion",
    attack: 7,
    health: 7,
    text: "7/7 holographic prism closer.",
    keywords: ["taunt"],
    art: "arcane",
  },
  {
    id: "night_stalker",
    name: "Night Ops",
    cost: 5,
    type: "minion",
    attack: 5,
    health: 3,
    text: "Lifesteal laser daggers. Charge.",
    keywords: ["lifesteal", "charge"],
    art: "shadow",
  },
  {
    id: "math_golem",
    name: "Logic Core",
    cost: 4,
    type: "minion",
    attack: 4,
    health: 4,
    text: "Perfect square. 4/4 equation reactor.",
    art: "arcane",
  },
  {
    id: "bolt",
    name: "Arc Bolt",
    cost: 1,
    type: "spell",
    text: "Deal 2 damage (orbital arc laser).",
    spell: { kind: "damage", amount: 2, target: "any" },
    art: "arcane",
  },
  {
    id: "firelance",
    name: "Discombobulator Beam",
    cost: 2,
    type: "spell",
    text: "Deal 3 damage with a multi-frequency laser.",
    spell: { kind: "damage", amount: 3, target: "enemy" },
    art: "ember",
  },
  {
    id: "reckoning",
    name: "Final Reckoning",
    cost: 4,
    type: "spell",
    text: "Deal 4 damage — judgment laser.",
    spell: { kind: "damage", amount: 4, target: "any" },
    art: "arcane",
  },
  {
    id: "sweep",
    name: "Sweep Laser",
    cost: 3,
    type: "spell",
    text: "Deal 2 to all enemy minions (laser grid).",
    spell: { kind: "damage", amount: 2, target: "all_enemy_minions" },
    art: "frost",
  },
  {
    id: "cataclysm",
    name: "Orbital Cataclysm",
    cost: 5,
    type: "spell",
    text: "Deal 3 to all enemies from orbit.",
    spell: { kind: "damage", amount: 3, target: "all_enemies" },
    art: "ember",
  },
  {
    id: "mend",
    name: "Nano Mend",
    cost: 2,
    type: "spell",
    text: "Restore 5 health (medical laser).",
    spell: { kind: "heal", amount: 5, target: "friendly_hero" },
    art: "nature",
  },
  {
    id: "temper",
    name: "Temper Field",
    cost: 2,
    type: "spell",
    text: "Give a friendly minion +2/+2 forge lasers.",
    spell: { kind: "buff", attack: 2, health: 2, target: "friendly_minion" },
    art: "steel",
  },
  {
    id: "insight",
    name: "Tactical Insight",
    cost: 1,
    type: "spell",
    text: "Draw 2 cards — HUD intel burst.",
    spell: { kind: "draw", count: 2 },
    art: "arcane",
  },
  {
    id: "scorch_study",
    name: "Scorch Analysis",
    cost: 3,
    type: "spell",
    text: "Deal 2 to an enemy. Draw a card.",
    spell: { kind: "damage_and_draw", damage: 2, draw: 1, target: "enemy" },
    art: "ember",
  },
  {
    id: "precise_cut",
    name: "Precision Laser",
    cost: 3,
    type: "spell",
    text: "Deal 5 damage to an enemy minion.",
    spell: { kind: "damage", amount: 5, target: "enemy_minion" },
    art: "shadow",
  },

  // Store exclusives — core vault
  {
    id: "dominus_reximus",
    name: "Dominus Reximus",
    cost: 10,
    type: "spell",
    storeExclusive: true,
    text:
      "Give a friendly Taunt minion +50/+50, Immune, and Reborn. Your other minions get +10/+10 and Immune this turn.",
    spell: {
      kind: "dominus_reximus",
      targetAttack: 50,
      targetHealth: 50,
      othersAttack: 10,
      othersHealth: 10,
    },
    art: "steel",
  },
  {
    id: "arc_catalyst",
    name: "Arc Catalyst",
    cost: 3,
    type: "spell",
    storeExclusive: true,
    text: "Gain +2 Spell Power (stacks with laser damage spells).",
    spell: { kind: "spell_power", amount: 2 },
    art: "arcane",
  },
  {
    id: "amplify_core",
    name: "Amplify Core",
    cost: 2,
    type: "spell",
    storeExclusive: true,
    text: "Gain +1 Spell Power (stacks). Draw a card.",
    spell: { kind: "spell_power", amount: 1, draw: 1 },
    art: "arcane",
  },
  {
    id: "overcharge",
    name: "Overcharge",
    cost: 4,
    type: "spell",
    storeExclusive: true,
    text: "Gain +3 Spell Power (stacks).",
    spell: { kind: "spell_power", amount: 3 },
    art: "ember",
  },
  {
    id: "titan_wrath",
    name: "Titan Wrath",
    cost: 6,
    type: "spell",
    storeExclusive: true,
    text: "Deal 6 (+Spell Power) — titan laser.",
    spell: { kind: "damage", amount: 6, target: "any" },
    art: "ember",
  },
  {
    id: "nova_hex",
    name: "Nova Hex",
    cost: 4,
    type: "spell",
    storeExclusive: true,
    text: "Deal 2 (+Spell Power) to all enemies.",
    spell: { kind: "damage", amount: 2, target: "all_enemies" },
    art: "shadow",
  },
  {
    id: "blood_pact",
    name: "Blood Pact",
    cost: 3,
    type: "spell",
    storeExclusive: true,
    text: "Deal 4 (+Spell Power). Restore 4 to your hero.",
    spell: { kind: "damage_heal", damage: 4, heal: 4, target: "enemy" },
    art: "shadow",
  },
  {
    id: "legion_horn",
    name: "Legion Signal",
    cost: 4,
    type: "spell",
    storeExclusive: true,
    text: "Give all friendly minions +2/+2 broadcast.",
    spell: { kind: "buff_all_friendly", attack: 2, health: 2 },
    art: "steel",
  },
  {
    id: "mirror_aegis",
    name: "Mirror Aegis",
    cost: 2,
    type: "spell",
    storeExclusive: true,
    text: "Give a friendly minion Immune this turn and Shield.",
    spell: { kind: "aegis", shield: true },
    art: "frost",
  },
  {
    id: "void_sovereign",
    name: "Void Sovereign",
    cost: 8,
    type: "minion",
    storeExclusive: true,
    attack: 6,
    health: 8,
    text: "Taunt. Immune. Reborn. Apex void armor.",
    keywords: ["taunt", "immune", "reborn"],
    art: "shadow",
  },
  {
    id: "siege_titan",
    name: "Siege Titan",
    cost: 7,
    type: "minion",
    storeExclusive: true,
    attack: 8,
    health: 10,
    text: "Taunt. 8/10 siege laser wall.",
    keywords: ["taunt"],
    art: "steel",
  },
  {
    id: "reaper_wraith",
    name: "Reaper Wraith",
    cost: 5,
    type: "minion",
    storeExclusive: true,
    attack: 6,
    health: 4,
    text: "Lifesteal. Reborn. Phase lasers.",
    keywords: ["lifesteal", "reborn"],
    art: "shadow",
  },
  {
    id: "grav_anchor",
    name: "Grav Anchor",
    cost: 4,
    type: "minion",
    storeExclusive: true,
    attack: 3,
    health: 7,
    text: "Taunt. Shield. Gravity projectors.",
    keywords: ["taunt", "shield"],
    art: "frost",
  },
  {
    id: "spellblade",
    name: "Spellblade",
    cost: 5,
    type: "minion",
    storeExclusive: true,
    attack: 5,
    health: 4,
    text: "Charge. Lifesteal. Arc-laser edge.",
    keywords: ["charge", "lifesteal"],
    art: "arcane",
  },

  // Store stock rotation wave A
  {
    id: "rail_sniper",
    name: "Rail Sniper",
    cost: 4,
    type: "minion",
    storeExclusive: true,
    attack: 5,
    health: 3,
    text: "Charge. Magnetic rail rifle opens lanes.",
    keywords: ["charge"],
    art: "ember",
  },
  {
    id: "pulse_grenade",
    name: "Pulse Grenade",
    cost: 3,
    type: "spell",
    storeExclusive: true,
    text: "Deal 3 (+Spell Power) to all enemy minions.",
    spell: { kind: "damage", amount: 3, target: "all_enemy_minions" },
    art: "ember",
  },
  {
    id: "phase_walker",
    name: "Phase Walker",
    cost: 3,
    type: "minion",
    storeExclusive: true,
    attack: 3,
    health: 3,
    text: "Rush. Reborn. Phases through first death.",
    keywords: ["rush", "reborn"],
    art: "shadow",
  },
  {
    id: "fortify_protocol",
    name: "Fortify Protocol",
    cost: 3,
    type: "spell",
    storeExclusive: true,
    text: "Give all friendly minions +1/+3 hex shields.",
    spell: { kind: "buff_all_friendly", attack: 1, health: 3 },
    art: "frost",
  },
  {
    id: "omega_drone",
    name: "Omega Drone",
    cost: 6,
    type: "minion",
    storeExclusive: true,
    attack: 5,
    health: 5,
    text: "Charge. Lifesteal. Twin plasma cannons.",
    keywords: ["charge", "lifesteal"],
    art: "ember",
  },
  {
    id: "rupture_field",
    name: "Rupture Field",
    cost: 4,
    type: "spell",
    storeExclusive: true,
    text: "Deal 2 (+Spell Power) to all enemies. Gravity tear.",
    spell: { kind: "damage", amount: 2, target: "all_enemies" },
    art: "shadow",
  },
  {
    id: "cryo_barricade",
    name: "Cryo Barricade",
    cost: 4,
    type: "minion",
    storeExclusive: true,
    attack: 2,
    health: 6,
    text: "Taunt. Shield. Cryo tower wall.",
    keywords: ["taunt", "shield"],
    art: "frost",
  },
  {
    id: "chain_surge",
    name: "Chain Surge",
    cost: 2,
    type: "spell",
    storeExclusive: true,
    text: "Deal 3 (+Spell Power) to an enemy. Draw a card.",
    spell: { kind: "damage_and_draw", damage: 3, draw: 1, target: "enemy" },
    art: "arcane",
  },
  {
    id: "nano_swarm",
    name: "Nano Swarm",
    cost: 5,
    type: "spell",
    storeExclusive: true,
    text: "Give all friendly minions +3/+3 nanite storm.",
    spell: { kind: "buff_all_friendly", attack: 3, health: 3 },
    art: "nature",
  },
  {
    id: "titan_edge",
    name: "Titan Edge",
    cost: 7,
    type: "minion",
    storeExclusive: true,
    attack: 7,
    health: 6,
    text: "Charge. Shield. Arc-greatsword closer.",
    keywords: ["charge", "shield"],
    art: "arcane",
  },

  // Store stock wave B — art already shipped; units enter rotation without version bump
  {
    id: "aegis_phalanx",
    name: "Aegis Phalanx",
    cost: 5,
    type: "minion",
    storeExclusive: true,
    attack: 3,
    health: 7,
    text: "Taunt. Shield. Linked barrier wall.",
    keywords: ["taunt", "shield"],
    art: "steel",
  },
  {
    id: "cryo_ward",
    name: "Cryo Ward",
    cost: 2,
    type: "spell",
    storeExclusive: true,
    text: "Give a friendly minion Immune this turn and +0/+3 frost plate.",
    spell: { kind: "aegis", shield: true },
    art: "frost",
  },
  {
    id: "ion_grid",
    name: "Ion Grid",
    cost: 4,
    type: "spell",
    storeExclusive: true,
    text: "Deal 2 (+Spell Power) to all enemy minions. Ion lattice.",
    spell: { kind: "damage", amount: 2, target: "all_enemy_minions" },
    art: "arcane",
  },
  {
    id: "ion_lance",
    name: "Ion Lance",
    cost: 3,
    type: "spell",
    storeExclusive: true,
    text: "Deal 4 (+Spell Power) — focused ion spear.",
    spell: { kind: "damage", amount: 4, target: "enemy" },
    art: "arcane",
  },
  {
    id: "phase_skirmisher",
    name: "Phase Skirmisher",
    cost: 2,
    type: "minion",
    storeExclusive: true,
    attack: 3,
    health: 2,
    text: "Rush. Flicker-frame infantry.",
    keywords: ["rush"],
    art: "shadow",
  },
  {
    id: "photon_barrage",
    name: "Photon Barrage",
    cost: 5,
    type: "spell",
    storeExclusive: true,
    text: "Deal 3 (+Spell Power) to all enemies. Photon storm.",
    spell: { kind: "damage", amount: 3, target: "all_enemies" },
    art: "ember",
  },
  {
    id: "pulse_sentinel",
    name: "Pulse Sentinel",
    cost: 3,
    type: "minion",
    storeExclusive: true,
    attack: 2,
    health: 4,
    text: "Taunt. Automated perimeter turret.",
    keywords: ["taunt"],
    art: "steel",
  },
  {
    id: "quantum_mend",
    name: "Quantum Mend",
    cost: 3,
    type: "spell",
    storeExclusive: true,
    text: "Restore 8 health — quantum med-beam.",
    spell: { kind: "heal", amount: 8, target: "friendly_hero" },
    art: "nature",
  },

  // Store stock wave C — rotation expansion (no package version bump)
  {
    id: "grav_well",
    name: "Grav Well",
    cost: 4,
    type: "spell",
    storeExclusive: true,
    text: "Deal 3 (+Spell Power) to all enemy minions. Gravity crush.",
    spell: { kind: "damage", amount: 3, target: "all_enemy_minions" },
    art: "shadow",
  },
  {
    id: "swarm_drone",
    name: "Swarm Drone",
    cost: 3,
    type: "minion",
    storeExclusive: true,
    attack: 2,
    health: 3,
    text: "Rush. Reborn. Nanite hive-mind unit.",
    keywords: ["rush", "reborn"],
    art: "nature",
  },
  {
    id: "nova_core",
    name: "Nova Core",
    cost: 6,
    type: "spell",
    storeExclusive: true,
    text: "Deal 4 (+Spell Power) to all enemies. Reactor breach.",
    spell: { kind: "damage", amount: 4, target: "all_enemies" },
    art: "ember",
  },
  {
    id: "shield_matrix",
    name: "Shield Matrix",
    cost: 4,
    type: "spell",
    storeExclusive: true,
    text: "Give all friendly minions +2/+2 and linked plating.",
    spell: { kind: "buff_all_friendly", attack: 2, health: 2 },
    art: "steel",
  },
  {
    id: "void_harvester",
    name: "Void Harvester",
    cost: 5,
    type: "minion",
    storeExclusive: true,
    attack: 4,
    health: 5,
    text: "Taunt. Lifesteal. Drains with every block.",
    keywords: ["taunt", "lifesteal"],
    art: "shadow",
  },
  {
    id: "plasma_saber",
    name: "Plasma Saber",
    cost: 4,
    type: "minion",
    storeExclusive: true,
    attack: 5,
    health: 3,
    text: "Charge. Superheated monomolecular edge.",
    keywords: ["charge"],
    art: "ember",
  },
  {
    id: "orbital_scan",
    name: "Orbital Scan",
    cost: 2,
    type: "spell",
    storeExclusive: true,
    text: "Gain +1 Spell Power. Draw 2 — satellite uplink.",
    spell: { kind: "spell_power", amount: 1, draw: 2 },
    art: "arcane",
  },
  {
    id: "bastion_prime",
    name: "Bastion Prime",
    cost: 6,
    type: "minion",
    storeExclusive: true,
    attack: 4,
    health: 8,
    text: "Taunt. Shield. Reborn. Capital fort-line.",
    keywords: ["taunt", "shield", "reborn"],
    art: "steel",
  },
  {
    id: "flicker_blade",
    name: "Flicker Blade",
    cost: 2,
    type: "minion",
    storeExclusive: true,
    attack: 2,
    health: 2,
    text: "Charge. Rush. Ultra-light phase knife.",
    keywords: ["charge", "rush"],
    art: "shadow",
  },
  {
    id: "singularity_bolt",
    name: "Singularity Bolt",
    cost: 5,
    type: "spell",
    storeExclusive: true,
    text: "Deal 5 (+Spell Power). Restore 3 — event horizon.",
    spell: { kind: "damage_heal", damage: 5, heal: 3, target: "enemy" },
    art: "shadow",
  },
];

export const CARD_MAP: Record<string, CardDef> = Object.fromEntries(
  CARD_POOL.map((c) => [c.id, c]),
);

export function getCard(id: string): CardDef {
  const c = CARD_MAP[id];
  if (!c) throw new Error(`Unknown card: ${id}`);
  return c;
}

export function cardArtSrc(id: string): string {
  return `/cards/${id}.jpg`;
}

export function classLabel(art: CardDef["art"]): string {
  switch (art) {
    case "steel":
      return "Ironclad";
    case "ember":
      return "Plasma";
    case "frost":
      return "Cryo";
    case "shadow":
      return "Voidops";
    case "nature":
      return "Bioforge";
    case "arcane":
      return "Arctech";
  }
}

export function typeLabel(type: CardDef["type"]): string {
  return type === "minion" ? "Unit" : "Protocol";
}

export function buildStarterDeck(): string[] {
  return [
    "squire",
    "squire",
    "spark_imp",
    "spark_imp",
    "warden",
    "warden",
    "arc_blade",
    "arc_blade",
    "frost_hound",
    "frost_hound",
    "shieldbearer",
    "blood_leech",
    "grove_keeper",
    "grove_keeper",
    "iron_colossus",
    "storm_rider",
    "math_golem",
    "math_golem",
    "void_knight",
    "ember_giant",
    "night_stalker",
    "prism_titan",
    "bolt",
    "bolt",
    "firelance",
    "firelance",
    "sweep",
    "mend",
    "insight",
    "temper",
    "scorch_study",
    "precise_cut",
    "reckoning",
    "cataclysm",
  ];
}

export function isStoreExclusive(id: string): boolean {
  return !!CARD_MAP[id]?.storeExclusive;
}

/** Wave A exclusives — weekly rotation core. */
export const STORE_STOCK_WAVE_IDS = [
  "rail_sniper",
  "pulse_grenade",
  "phase_walker",
  "fortify_protocol",
  "omega_drone",
  "rupture_field",
  "cryo_barricade",
  "chain_surge",
  "nano_swarm",
  "titan_edge",
] as const;

/** Wave B exclusives — alternate spotlight pool (existing art stock). */
export const STORE_STOCK_WAVE_B_IDS = [
  "aegis_phalanx",
  "cryo_ward",
  "ion_grid",
  "ion_lance",
  "phase_skirmisher",
  "photon_barrage",
  "pulse_sentinel",
  "quantum_mend",
] as const;

/** Wave C exclusives — expansion stock; rotates with A/B without version bump. */
export const STORE_STOCK_WAVE_C_IDS = [
  "grav_well",
  "swarm_drone",
  "nova_core",
  "shield_matrix",
  "void_harvester",
  "plasma_saber",
  "orbital_scan",
  "bastion_prime",
  "flicker_blade",
  "singularity_bolt",
] as const;

/** Combined stock used by rotation spotlighting. */
export const ALL_STOCK_WAVE_IDS = [
  ...STORE_STOCK_WAVE_IDS,
  ...STORE_STOCK_WAVE_B_IDS,
  ...STORE_STOCK_WAVE_C_IDS,
] as const;

export function minionValueScore(attack: number, health: number, cost: number): number {
  if (cost <= 0) return attack + health;
  return Math.round(((attack + health) / cost) * 100) / 100;
}

export function keywordLabel(k: string): string {
  switch (k) {
    case "taunt":
      return "Taunt";
    case "charge":
      return "Charge";
    case "shield":
      return "Shield";
    case "lifesteal":
      return "Lifesteal";
    case "rush":
      return "Rush";
    case "immune":
      return "Immune";
    case "reborn":
      return "Reborn";
    default:
      return k;
  }
}
